version: "3"
services:
  my-web-application:
    image: fabiomerli/get-started:v_1.0.0
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3500:80"
    networks:
      - webnet
networks:
  webnet:
